# Generated by Django 4.2.7 on 2026-01-08 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this connection', max_length=255)),
                ('db_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlserver', 'SQL Server')], help_text='Database type', max_length=20)),
                ('host', models.CharField(help_text='Database host address', max_length=255)),
                ('port', models.IntegerField(help_text='Database port number')),
                ('username', models.CharField(help_text='Database username', max_length=255)),
                ('password', models.TextField(help_text='Encrypted database password')),
                ('database_name', models.CharField(help_text='Database name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connection is active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Connection',
                'verbose_name_plural': 'Database Connections',
                'db_table': 'database_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionTestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], help_text='Test result status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if test failed', null=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True, help_text='When the test was performed')),
                ('connection', models.ForeignKey(help_text='The connection that was tested', on_delete=django.db.models.deletion.CASCADE, related_name='test_logs', to='connections.databaseconnection')),
                ('tested_by', models.ForeignKey(blank=True, help_text='User who performed the test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connection Test Log',
                'verbose_name_plural': 'Connection Test Logs',
                'db_table': 'connection_test_logs',
                'ordering': ['-tested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='databaseconnection',
            index=models.Index(fields=['created_by', 'is_active'], name='database_co_created_0b9ece_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseconnection',
            index=models.Index(fields=['db_type', 'is_active'], name='database_co_db_type_7b0a89_idx'),
        ),
        migrations.AddIndex(
            model_name='connectiontestlog',
            index=models.Index(fields=['connection', '-tested_at'], name='connection__connect_e69733_idx'),
        ),
        migrations.AddIndex(
            model_name='connectiontestlog',
            index=models.Index(fields=['status', '-tested_at'], name='connection__status_aa3d2e_idx'),
        ),
    ]
