# Generated by Django 4.2 on 2026-01-14 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (Admin user) who owns this connection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='databaseconnection',
            index=models.Index(fields=['tenant'], name='database_co_tenant__5e45b4_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseconnection',
            index=models.Index(fields=['tenant', 'is_active'], name='database_co_tenant__fe3080_idx'),
        ),
    ]
