# Generated by Django 4.2 on 2026-01-27 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0004_make_tenant_required_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlserver', 'SQL Server'), ('clickhouse', 'ClickHouse')], help_text='Database type', max_length=20),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (Admin user) who owns this connection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
