# Generated by Django 4.2 on 2026-01-15 06:28

from django.db import migrations


def fix_null_tenants(apps, schema_editor):
    """Fix any remaining null tenant values"""
    DatabaseConnection = apps.get_model('connections', 'DatabaseConnection')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    # Find all connections with null tenant
    connections_with_null_tenant = DatabaseConnection.objects.filter(tenant__isnull=True)
    
    for conn in connections_with_null_tenant:
        try:
            profile = UserProfile.objects.get(user=conn.created_by)
            if profile.role == 'admin':
                conn.tenant = conn.created_by
            elif profile.role == 'super_admin':
                # Super Admin: use themselves as tenant
                conn.tenant = conn.created_by
            elif profile.tenant:
                conn.tenant = profile.tenant
            else:
                # Fallback: use created_by as tenant
                conn.tenant = conn.created_by
            conn.save()
        except UserProfile.DoesNotExist:
            # Fallback: use created_by as tenant
            conn.tenant = conn.created_by
            conn.save()
        except Exception:
            # Last resort: use created_by as tenant
            conn.tenant = conn.created_by
            conn.save()


def reverse_fix_null_tenants(apps, schema_editor):
    """Reverse migration - no-op"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_populate_connection_tenant'),
    ]

    operations = [
        migrations.RunPython(fix_null_tenants, reverse_fix_null_tenants),
    ]
