# Generated by Django 4.2 on 2026-01-29 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0005_alter_databaseconnection_db_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this connection', max_length=255)),
                ('api_type', models.CharField(choices=[('zoho_crm', 'Zoho CRM')], help_text='API type', max_length=50)),
                ('client_id', models.CharField(help_text='OAuth Client ID', max_length=255)),
                ('client_secret', models.TextField(help_text='Encrypted OAuth Client Secret')),
                ('refresh_token', models.TextField(help_text='Encrypted OAuth Refresh Token')),
                ('api_domain', models.CharField(help_text='Zoho API domain', max_length=255)),
                ('token_url', models.CharField(help_text='OAuth token URL', max_length=255)),
                ('selected_modules', models.JSONField(default=list, help_text='List of selected module names for syncing')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connection is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this connection', on_delete=django.db.models.deletion.CASCADE, related_name='created_api_connections', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant (Admin user) who owns this connection', on_delete=django.db.models.deletion.CASCADE, related_name='api_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Connection',
                'verbose_name_plural': 'API Connections',
                'db_table': 'api_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apiconnection',
            index=models.Index(fields=['tenant', 'is_active'], name='api_connect_tenant__f7a04f_idx'),
        ),
        migrations.AddIndex(
            model_name='apiconnection',
            index=models.Index(fields=['api_type', 'is_active'], name='api_connect_api_typ_1a7b57_idx'),
        ),
        migrations.AddIndex(
            model_name='apiconnection',
            index=models.Index(fields=['created_by', 'is_active'], name='api_connect_created_11735e_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiconnection',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_api_connection_name_per_tenant'),
        ),
    ]
