# Generated by Django 4.2 on 2026-01-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_apiconnection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconnection',
            name='selected_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of selected module names for syncing', null=True),
        ),
    ]
