# Generated by Django 4.2 on 2026-02-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0008_add_last_tested_at_to_connections"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconnection",
            name="sap_base_url",
            field=models.CharField(
                blank=True,
                help_text="SAP Business One Service Layer base URL (e.g. https://server:50000/b1s/v2/)",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apiconnection",
            name="sap_endpoints",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Selected SAP document types/endpoints for sync",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apiconnection",
            name="sap_password",
            field=models.TextField(
                blank=True, help_text="SAP password (encrypted at rest)", null=True
            ),
        ),
        migrations.AddField(
            model_name="apiconnection",
            name="sap_username",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='SAP UserName and CompanyDB (stored as JSON: {"UserName": "...", "CompanyDB": "..."})',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="api_domain",
            field=models.CharField(
                blank=True, help_text="Zoho API domain", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="api_type",
            field=models.CharField(
                choices=[("zoho_crm", "Zoho CRM"), ("sap_b1", "SAP Business One")],
                help_text="API type",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="client_id",
            field=models.CharField(
                blank=True, help_text="OAuth Client ID", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="client_secret",
            field=models.TextField(
                blank=True, help_text="Encrypted OAuth Client Secret", null=True
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="refresh_token",
            field=models.TextField(
                blank=True, help_text="Encrypted OAuth Refresh Token", null=True
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="token_url",
            field=models.CharField(
                blank=True, help_text="OAuth token URL", max_length=255, null=True
            ),
        ),
    ]
