# Generated by Django 4.2 on 2026-03-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0009_add_sap_api_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconnection",
            name="azure_client_id",
            field=models.CharField(
                blank=True,
                help_text="Azure DevOps Service Principal Application (client) ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apiconnection",
            name="azure_client_secret",
            field=models.TextField(
                blank=True,
                help_text="Azure DevOps Client Secret (encrypted at rest)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apiconnection",
            name="azure_tenant_id",
            field=models.CharField(
                blank=True,
                help_text="Azure AD Tenant ID (GUID)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apiconnection",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Azure DevOps organization name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="api_type",
            field=models.CharField(
                choices=[
                    ("zoho_crm", "Zoho CRM"),
                    ("sap_b1", "SAP Business One"),
                    ("azure_devops", "Azure DevOps"),
                ],
                help_text="API type",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="databaseconnection",
            name="db_type",
            field=models.CharField(
                choices=[
                    ("postgres", "PostgreSQL"),
                    ("mysql", "MySQL"),
                    ("sqlserver", "SQL Server"),
                    ("clickhouse", "ClickHouse"),
                    ("oracle_adw", "Oracle ADW"),
                ],
                help_text="Database type",
                max_length=20,
            ),
        ),
    ]
