# Generated by Django 4.2 on 2026-03-24 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connections", "0010_add_azure_devops_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileSourceConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this file source", max_length=255
                    ),
                ),
                (
                    "relative_path",
                    models.CharField(
                        help_text="Path relative to FILE_SYNC_ROOT on the application server",
                        max_length=1024,
                    ),
                ),
                (
                    "delimiter",
                    models.CharField(
                        default=",",
                        help_text="CSV delimiter character (single character only)",
                        max_length=1,
                    ),
                ),
                (
                    "encoding",
                    models.CharField(
                        default="utf-8",
                        help_text="File encoding (e.g., utf-8, utf-16, latin-1)",
                        max_length=64,
                    ),
                ),
                (
                    "has_header",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the first row contains column headers",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this file source is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this file source connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_file_source_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant (Admin user) who owns this file source connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_source_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File Source Connection",
                "verbose_name_plural": "File Source Connections",
                "db_table": "file_source_connections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="filesourceconnection",
            index=models.Index(
                fields=["tenant", "is_active"], name="file_source_tenant__622806_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filesourceconnection",
            index=models.Index(
                fields=["created_by", "is_active"],
                name="file_source_created_0b4547_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="filesourceconnection",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"),
                name="unique_file_source_connection_name_per_tenant",
            ),
        ),
    ]
