# Generated by Django 4.2 on 2026-04-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0011_filesourceconnection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseconnection",
            name="db_type",
            field=models.CharField(
                choices=[
                    ("postgres", "PostgreSQL"),
                    ("mysql", "MySQL"),
                    ("sqlserver", "SQL Server"),
                    ("clickhouse", "ClickHouse"),
                    ("oracle_adw", "Oracle ADW"),
                    ("mongodb", "MongoDB"),
                ],
                help_text="Database type",
                max_length=20,
            ),
        ),
    ]
