# Generated by Django 4.2 on 2026-05-12 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connections", "0013_filesource_multiformat"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionHealthCheckLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tested_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("total_tested", models.IntegerField(default=0)),
                ("total_passed", models.IntegerField(default=0)),
                ("total_failed", models.IntegerField(default=0)),
                (
                    "results_json",
                    models.JSONField(
                        default=dict,
                        help_text="Full health check results including all connection details",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_check_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "connection_health_check_log",
                "ordering": ["-tested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="connectionhealthchecklog",
            index=models.Index(fields=["-tested_at"], name="health_tested_at_idx"),
        ),
    ]
