"""
Django settings for dbsync_tool project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from cryptography.fernet import Fernet
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bx@5l*4o3ggud$prerb0dmw35pksy(&u@lv(hahmdp4!*n_9m9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # For humanize template filters (intcomma, timesince, etc.)
    'rest_framework',
    'accounts',
    'connections',
    'core',
    'metadata',
    'sync_jobs',
    'scheduler.apps.SchedulerConfig',  # Scheduler app using APScheduler (no Celery/Redis needed)
    # 'django_celery_beat',  # Removed - using APScheduler instead
    # 'django_celery_results',  # Removed - using APScheduler instead
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'core.middleware.error_logging.ErrorLoggingMiddleware',  # Error logging with correlation IDs
    'core.middleware.request_validation.RequestValidationMiddleware',  # Request validation
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Must be before rate_limiting (adds request.user)
    'core.middleware.rate_limiting.RateLimitingMiddleware',  # Rate limiting (needs request.user)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dbsync_tool.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dbsync_tool.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Local development / test convenience:
# - If DB_ENGINE is set to `postgres|postgresql`, use Postgres.
# - If DB_ENGINE is set to `sqlite|sqlite3` (or unset), default to SQLite.
DB_ENGINE = os.environ.get("DB_ENGINE", "").strip().lower()

DATABASES = {}

if DB_ENGINE in {"postgres", "postgresql", "pg"}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'tauseef'),
            'USER': os.environ.get('POSTGRES_USER', 'migration_user'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'StrongPassword123'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    # Default to SQLite so unit tests can run without external Postgres.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }

# Cache Configuration
# Using LocMemCache for development (in-memory cache)
# For production, consider using Redis: 'django.core.cache.backends.redis.RedisCache'
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 10000,  # Maximum number of cache entries
        },
        'TIMEOUT': 300,  # Default timeout (5 minutes)
    }
}

# Metadata Cache Configuration
METADATA_CACHE_TTL = 300  # 5 minutes for tables and columns
SCHEMA_CACHE_TTL = 600    # 10 minutes for schemas (change less frequently)

# Celery Configuration - REMOVED
# Using APScheduler instead (no Redis/Celery needed)
# All scheduled jobs are managed by scheduler.service using APScheduler BackgroundScheduler

# Email Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'saadpractice4@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'txludusmznqxoweo')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'saadpractice4@gmail.com')
ADMIN_EMAILS = [
    email.strip()
    for email in os.environ.get(
        "ADMIN_EMAILS",
        "saadpractice4@gmail.com,saad.sayyed@actin.co.in",
    ).split(",")
    if email.strip()
]

# Site URL for email links
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8005')

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # India Standard Time (IST, GMT+5:30)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Flat-file sync root (server-side path only).
# CSV source paths must be provided relative to this directory.
FILE_SYNC_ROOT = Path(os.environ.get('FILE_SYNC_ROOT', str(BASE_DIR / 'file_sources')))
FILE_SYNC_STRICT = os.environ.get('FILE_SYNC_STRICT', 'True').lower() == 'true'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Encryption key for password encryption
# Generate a key: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Store in environment variable or set here (NOT recommended for production)
# IMPORTANT: This key must remain constant or all encrypted passwords will be unreadable
ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY', None)
if not ENCRYPTION_KEY:
    # For development only - use a fixed key so passwords remain decryptable
    # In production, set ENCRYPTION_KEY environment variable
    # This key was generated once and must remain constant
    ENCRYPTION_KEY = 'wTsfowuOCFw9lLEnhYV-9oMCvWCKyZxJRMEUOPtf3MU='
    print(f"WARNING: Using development encryption key. Set ENCRYPTION_KEY environment variable for production!")

# Production Settings
if not DEBUG:
    # Security settings
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Logging
    # Ensure logs directory exists
    import os
    logs_dir = BASE_DIR.parent / 'logs'
    os.makedirs(logs_dir, exist_ok=True)
    
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
            'json': {
                'format': '%(asctime)s %(name)s %(levelname)s %(message)s %(pathname)s %(lineno)d',
            },
            'structured': {
                'format': '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s"}',
            },
        },
        'handlers': {
            'file': {
                'level': 'INFO',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'dbsync.log',
                'maxBytes': 1024 * 1024 * 10,  # 10 MB
                'backupCount': 5,
                'formatter': 'verbose',
            },
            'rbac_audit': {
                'level': 'INFO',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'rbac_audit.log',
                'maxBytes': 1024 * 1024 * 10,  # 10 MB
                'backupCount': 5,
                'formatter': 'json',
            },
            'audit': {
                'level': 'INFO',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR.parent / 'logs' / 'audit.log',
                'maxBytes': 1024 * 1024 * 10,  # 10 MB
                'backupCount': 5,
                'formatter': 'structured',
            },
            'error': {
                'level': 'ERROR',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR.parent / 'logs' / 'error.log',
                'maxBytes': 1024 * 1024 * 10,  # 10 MB
                'backupCount': 5,
                'formatter': 'structured',
            },
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
            'sync_engine': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
            'scheduler': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
            'accounts': {
                'handlers': ['file', 'rbac_audit', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
            'accounts.views': {
                'handlers': ['file', 'rbac_audit', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
            'accounts.services': {
                'handlers': ['file', 'rbac_audit', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
            'accounts.permissions': {
                'handlers': ['file', 'rbac_audit', 'console'],
                'level': 'WARNING',
                'propagate': False,
            },
            'connections': {
                'handlers': ['file', 'rbac_audit', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
            'sync_jobs': {
                'handlers': ['file', 'rbac_audit', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
        'root': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
        },
    }
else:
    # Development logging - use same config as production
    pass  # Already defined above
