# Generated by Django 4.2 on 2026-01-08 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to=settings.AUTH_USER_MODEL)),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_jobs', to='connections.databaseconnection')),
                ('target_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_jobs', to='connections.databaseconnection')),
            ],
            options={
                'db_table': 'sync_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncJobTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('incremental_column', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='sync_jobs.syncjob')),
            ],
            options={
                'db_table': 'sync_job_tables',
                'unique_together': {('job', 'schema_name', 'table_name')},
            },
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['status'], name='sync_jobs_status_4165fd_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['created_by', 'status'], name='sync_jobs_created_68a830_idx'),
        ),
    ]
