# Generated by Django 4.2 on 2026-01-08 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sync_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(choices=[('once', 'Once'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Cron')], default='once', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text="Cron expression for custom schedules (e.g., '0 0 * * *' for daily at midnight)", max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='sync_jobs.syncjob')),
            ],
            options={
                'db_table': 'sync_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('last_value', models.TextField(blank=True, help_text='Last synced value (timestamp or ID) for incremental sync', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='sync_jobs.syncjob')),
            ],
            options={
                'db_table': 'sync_checkpoints',
            },
        ),
        migrations.AddIndex(
            model_name='synccheckpoint',
            index=models.Index(fields=['job', 'schema_name', 'table_name'], name='sync_checkp_job_id_4bd0c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='synccheckpoint',
            unique_together={('job', 'schema_name', 'table_name')},
        ),
    ]
