# Generated by Django 4.2 on 2026-01-08 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sync_jobs', '0002_syncschedule_synccheckpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_tables', models.IntegerField(default=0)),
                ('completed_tables', models.IntegerField(default=0)),
                ('total_rows_synced', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='sync_jobs.syncjob')),
            ],
            options={
                'db_table': 'sync_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rows_fetched', models.BigIntegerField(default=0)),
                ('rows_inserted', models.BigIntegerField(default=0)),
                ('batch_number', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sync_jobs.syncexecution')),
            ],
            options={
                'db_table': 'sync_execution_logs',
                'ordering': ['started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncexecutionlog',
            index=models.Index(fields=['execution', '-started_at'], name='sync_execut_executi_9cab34_idx'),
        ),
        migrations.AddIndex(
            model_name='syncexecutionlog',
            index=models.Index(fields=['status'], name='sync_execut_status_c74b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='syncexecution',
            index=models.Index(fields=['job', '-started_at'], name='sync_execut_job_id_5fb5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='syncexecution',
            index=models.Index(fields=['status'], name='sync_execut_status_970d29_idx'),
        ),
    ]
