# Generated by Django 4.2.7 on 2026-01-12 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync_jobs', '0003_syncexecution_syncexecutionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncexecution',
            name='avg_batch_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncexecution',
            name='memory_peak_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncexecution',
            name='query_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('notify_on_job_completed', models.BooleanField(default=True)),
                ('notify_on_job_failed', models.BooleanField(default=True)),
                ('notify_on_job_paused', models.BooleanField(default=False)),
                ('notify_on_schedule_missed', models.BooleanField(default=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sync_type', models.CharField(default='full', max_length=20)),
                ('table_config', models.JSONField(default=dict)),
                ('schedule_config', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_templates', to='connections.databaseconnection')),
                ('target_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_templates', to='connections.databaseconnection')),
            ],
            options={
                'db_table': 'job_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('job_completed', 'Job Completed'), ('job_failed', 'Job Failed'), ('job_paused', 'Job Paused'), ('schedule_missed', 'Schedule Missed')], max_length=50)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sync_jobs.syncexecution')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sync_jobs.syncjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7b6cc3_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_0cc56e_idx')],
            },
        ),
    ]
