# Generated by Django 4.2 on 2026-01-14 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync_jobs', '0004_syncexecution_avg_batch_time_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (Admin user) who owns this job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (Admin user) who owns this schedule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['tenant'], name='sync_jobs_tenant__ecd3e0_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['tenant', 'status'], name='sync_jobs_tenant__5f9298_idx'),
        ),
        migrations.AddIndex(
            model_name='syncschedule',
            index=models.Index(fields=['tenant'], name='sync_schedu_tenant__d0ed40_idx'),
        ),
        migrations.AddIndex(
            model_name='syncschedule',
            index=models.Index(fields=['tenant', 'is_enabled'], name='sync_schedu_tenant__55be51_idx'),
        ),
    ]
