# Generated by Django 4.2 on 2026-01-15 06:28

from django.db import migrations


def fix_null_job_tenants(apps, schema_editor):
    """Fix any remaining null tenant values in sync jobs"""
    SyncJob = apps.get_model('sync_jobs', 'SyncJob')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    # Find all jobs with null tenant
    jobs_with_null_tenant = SyncJob.objects.filter(tenant__isnull=True)
    
    for job in jobs_with_null_tenant:
        try:
            profile = UserProfile.objects.get(user=job.created_by)
            if profile.role == 'admin':
                job.tenant = job.created_by
            elif profile.role == 'super_admin':
                # Super Admin: use themselves as tenant
                job.tenant = job.created_by
            elif profile.tenant:
                job.tenant = profile.tenant
            else:
                # Fallback: use created_by as tenant
                job.tenant = job.created_by
            job.save()
        except UserProfile.DoesNotExist:
            # Fallback: use created_by as tenant
            job.tenant = job.created_by
            job.save()
        except Exception:
            # Last resort: use created_by as tenant
            job.tenant = job.created_by
            job.save()


def reverse_fix_null_job_tenants(apps, schema_editor):
    """Reverse migration - no-op"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sync_jobs', '0007_populate_schedule_tenant'),
    ]

    operations = [
        migrations.RunPython(fix_null_job_tenants, reverse_fix_null_job_tenants),
    ]
