# Generated by Django 4.2 on 2026-01-16 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync_jobs', '0009_make_tenant_required_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjobtable',
            name='column_transformations',
            field=models.JSONField(blank=True, default=dict, help_text='Column-level transformations (e.g., {"name": "TRIM", "email": "UPPER"})', null=True),
        ),
        migrations.AddField(
            model_name='syncjobtable',
            name='transformation_query',
            field=models.TextField(blank=True, help_text='WHERE clause for data filtering (e.g., "date_col >= \'2010-01-01\'")', null=True),
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (Admin user) who owns this job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (Admin user) who owns this schedule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
