# Generated by Django 4.2 on 2026-01-15 06:30

from django.db import migrations


def fix_null_schedule_tenants(apps, schema_editor):
    """Fix any remaining null tenant values in sync schedules"""
    SyncSchedule = apps.get_model('sync_jobs', 'SyncSchedule')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    # Find all schedules with null tenant
    schedules_with_null_tenant = SyncSchedule.objects.filter(tenant__isnull=True)
    
    for schedule in schedules_with_null_tenant:
        # First try to get from job
        if schedule.job and schedule.job.tenant:
            schedule.tenant = schedule.job.tenant
            schedule.save()
        elif schedule.job and schedule.job.created_by:
            # Fallback: get from job's created_by
            try:
                profile = UserProfile.objects.get(user=schedule.job.created_by)
                if profile.role == 'admin':
                    schedule.tenant = schedule.job.created_by
                elif profile.role == 'super_admin':
                    schedule.tenant = schedule.job.created_by
                elif profile.tenant:
                    schedule.tenant = profile.tenant
                else:
                    schedule.tenant = schedule.job.created_by
                schedule.save()
            except UserProfile.DoesNotExist:
                schedule.tenant = schedule.job.created_by
                schedule.save()
            except Exception:
                schedule.tenant = schedule.job.created_by
                schedule.save()


def reverse_fix_null_schedule_tenants(apps, schema_editor):
    """Reverse migration - no-op"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sync_jobs', '0008_make_tenant_required_job'),  # After job tenant is fixed
    ]

    operations = [
        migrations.RunPython(fix_null_schedule_tenants, reverse_fix_null_schedule_tenants),
    ]
