# Generated by Django 4.2 on 2026-01-30 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


def set_source_connection_type_for_existing_jobs(apps, schema_editor):
    """
    Data migration: Set source_connection_type='database' for all existing jobs
    """
    SyncJob = apps.get_model('sync_jobs', 'SyncJob')
    SyncJob.objects.filter(source_connection_type__isnull=True).update(source_connection_type='database')


def reverse_set_source_connection_type(apps, schema_editor):
    """
    Reverse migration: Set source_connection_type to None (not needed, but for completeness)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_alter_apiconnection_selected_modules'),
        ('sync_jobs', '0010_add_transformation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='source_api_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_source_jobs', to='connections.apiconnection'),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='source_connection_type',
            field=models.CharField(blank=True, choices=[('database', 'Database'), ('api', 'API')], help_text='Type of source connection (database or API)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='source_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_jobs', to='connections.databaseconnection'),
        ),
        # Data migration: Set source_connection_type for existing jobs
        migrations.RunPython(
            code=set_source_connection_type_for_existing_jobs,
            reverse_code=reverse_set_source_connection_type,
        ),
        migrations.CreateModel(
            name='APISyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(help_text='Name of the API module being synced', max_length=255)),
                ('last_sync_time', models.DateTimeField(blank=True, help_text='Last time this module was synced', null=True)),
                ('last_modified_time', models.DateTimeField(blank=True, help_text='Last modified time from API (for incremental sync)', null=True)),
                ('records_synced', models.BigIntegerField(default=0, help_text='Total number of records synced for this module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sync_states', to='sync_jobs.syncjob')),
            ],
            options={
                'db_table': 'api_sync_states',
                'ordering': ['job', 'module_name'],
            },
        ),
        migrations.AddIndex(
            model_name='apisyncstate',
            index=models.Index(fields=['job', 'module_name'], name='api_sync_st_job_id_b66aec_idx'),
        ),
        migrations.AddIndex(
            model_name='apisyncstate',
            index=models.Index(fields=['job'], name='api_sync_st_job_id_9fa71c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apisyncstate',
            unique_together={('job', 'module_name')},
        ),
    ]
