# Generated by Django 4.2 on 2026-01-28 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync_jobs', '0010_add_transformation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(help_text='Overall health score (0-100)')),
                ('components', models.JSONField(default=dict, help_text='Breakdown: {success_rate: 85, connection_health: 90, schedule_adherence: 75, error_frequency: 80}')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this snapshot was calculated')),
                ('tenant', models.ForeignKey(help_text='Tenant (Admin user) this score belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_score_snapshots',
                'ordering': ['-calculated_at'],
                'get_latest_by': 'calculated_at',
            },
        ),
        migrations.AddIndex(
            model_name='healthscoresnapshot',
            index=models.Index(fields=['tenant', '-calculated_at'], name='health_scor_tenant__1d4f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='healthscoresnapshot',
            index=models.Index(fields=['calculated_at'], name='health_scor_calcula_54b9e8_idx'),
        ),
    ]
