# Generated by Django 4.2 on 2026-01-28 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync_jobs', '0011_healthscoresnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('duration_spike', 'Duration Spike'), ('failure_pattern', 'Failure Pattern'), ('row_count_drop', 'Row Count Drop'), ('connection_timeout', 'Connection Timeout')], help_text='Type of anomaly detected', max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', help_text='Severity level of the anomaly', max_length=20)),
                ('description', models.TextField(help_text='Human-readable description of the anomaly')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this anomaly was detected')),
                ('is_acknowledged', models.BooleanField(db_index=True, default=False, help_text='Whether user has acknowledged this alert')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When this alert was acknowledged', null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='User who acknowledged this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_anomalies', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='Job this anomaly is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='sync_jobs.syncjob')),
                ('tenant', models.ForeignKey(help_text='Tenant (Admin user) this alert belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'anomaly_alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['tenant', '-detected_at'], name='anomaly_ale_tenant__57c095_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['tenant', 'is_acknowledged'], name='anomaly_ale_tenant__8a3e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['job', '-detected_at'], name='anomaly_ale_job_id_bd7766_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['severity', 'is_acknowledged'], name='anomaly_ale_severit_de876e_idx'),
        ),
    ]
