# Generated by Django 4.2 on 2026-02-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0011_syncjob_source_api_connection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apisyncstate",
            name="record_hashes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Map of record_id -> hash for hash-based change detection (e.g. SAP incremental)",
                null=True,
            ),
        ),
    ]
