# Generated by Django 4.2 on 2026-01-29 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync_jobs', '0012_anomalyalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshnessMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_successful_sync', models.DateTimeField(blank=True, db_index=True, help_text='When the last successful sync completed', null=True)),
                ('freshness_minutes', models.IntegerField(default=0, help_text='Minutes since last successful sync')),
                ('expected_freshness_minutes', models.IntegerField(default=1440, help_text='Expected freshness interval in minutes (based on schedule)')),
                ('freshness_status', models.CharField(choices=[('fresh', 'Fresh'), ('stale', 'Stale'), ('critical', 'Critical'), ('never_run', 'Never Run')], db_index=True, default='never_run', help_text='Freshness status category', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this metric was last updated')),
                ('job', models.OneToOneField(help_text='Job this metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='freshness_metric', to='sync_jobs.syncjob')),
                ('tenant', models.ForeignKey(help_text='Tenant (Admin user) this metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='freshness_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'freshness_metrics',
                'ordering': ['-freshness_minutes'],
            },
        ),
        migrations.AddIndex(
            model_name='freshnessmetric',
            index=models.Index(fields=['tenant', '-freshness_minutes'], name='freshness_m_tenant__9f7f94_idx'),
        ),
        migrations.AddIndex(
            model_name='freshnessmetric',
            index=models.Index(fields=['tenant', 'freshness_status'], name='freshness_m_tenant__bb9120_idx'),
        ),
        migrations.AddIndex(
            model_name='freshnessmetric',
            index=models.Index(fields=['job', '-updated_at'], name='freshness_m_job_id_81c09a_idx'),
        ),
    ]
