# Generated by Django for Day 6 Oracle validation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0012_add_api_sync_state_record_hashes"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncexecutionlog",
            name="verification_summary",
            field=models.TextField(
                blank=True,
                help_text="Post-migration verification summary (e.g. Rows: 100/100, Perfect accuracy: Yes)",
                null=True,
            ),
        ),
    ]
