# Generated by Django 4.2 on 2026-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0013_syncexecutionlog_verification_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjobtable",
            name="column_type_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-column target data type overrides (e.g., {"id": "NUMBER(10)", "name": "VARCHAR2(100)"})',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="syncexecutionlog",
            name="verification_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
