# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0014_syncjobtable_column_type_overrides_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="target_table_prefix",
            field=models.CharField(
                blank=True,
                help_text="Optional prefix for target table names (e.g. POST → POST_tablename)",
                max_length=64,
                null=True,
            ),
        ),
    ]
