# Generated by Django 4.2

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0015_syncjob_target_table_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncschedule",
            name="interval_hours",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="For hourly schedules: run every N hours on the first-run anchor grid (1-24).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
    ]
