# Generated by Django 4.2 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0016_syncschedule_interval_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjobtable",
            name="column_name_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-column target column name overrides (e.g., {"id": "customer_id"})',
                null=True,
            ),
        ),
    ]

