# Generated by Django 4.2 on 2026-03-24 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0011_filesourceconnection_and_more"),
        ("sync_jobs", "0017_syncjobtable_column_name_overrides_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="source_file_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_source_jobs",
                to="connections.filesourceconnection",
            ),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="source_connection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("database", "Database"),
                    ("api", "API"),
                    ("flat_file", "Flat file"),
                ],
                help_text="Type of source connection (database, API, or flat file)",
                max_length=20,
                null=True,
            ),
        ),
    ]
