# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0019_syncjobtable_excluded_columns_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjobtable",
            name="transform_plan",
            field=models.JSONField(
                blank=True,
                help_text="Model-data transform contract: mode (single_table|join|union|lookup), base_table, join_nodes, union_branches, union_select_columns, lookup block, selected_output_columns, structured_filters (no raw SQL), order_by, source_db_type.",
                null=True,
            ),
        ),
    ]
