# Generated by Django 4.2 on 2026-03-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0020_syncjobtable_transform_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="incremental_overlap_seconds",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Safety overlap window for incremental re-reads (seconds). Used to reduce missed rows around equal/low-precision watermark boundaries.",
            ),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="no_delete_propagation",
            field=models.BooleanField(
                default=True,
                help_text="When true, incremental sync will not propagate source-side deletes to target.",
            ),
        ),
        migrations.AddField(
            model_name="syncjobtable",
            name="incremental_key_columns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional ordered key columns for incremental upsert policy. If empty, runtime uses source PK or fallback policy.",
                null=True,
            ),
        ),
    ]
