# Generated by Django 4.2 on 2026-03-31 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0021_syncjob_incremental_overlap_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjobtable",
            name="flat_file_allow_hash_only_without_key",
            field=models.BooleanField(
                default=False,
                help_text="Allow hash-only dedup semantics when stable key columns are not configured for flat-file hybrid incremental mode.",
            ),
        ),
        migrations.AddField(
            model_name="syncjobtable",
            name="flat_file_hash_algorithm",
            field=models.CharField(
                default="sha256",
                help_text="Hash algorithm for flat-file row/file hashing (default: sha256).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="syncjobtable",
            name="flat_file_hash_columns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional source-column allowlist used to build deterministic row hashes for flat-file hybrid incremental mode. Empty means all effective columns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="syncjobtable",
            name="flat_file_incremental_mode",
            field=models.CharField(
                choices=[("legacy_mtime", "Legacy mtime"), ("hybrid_hash_control", "Hybrid hash + control table")],
                default="legacy_mtime",
                help_text="Flat-file incremental strategy. 'legacy_mtime' keeps existing checkpoint watermark behavior; 'hybrid_hash_control' enables file-hash control tracking and row-hash change detection.",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="FlatFileIngestionControl",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=1024)),
                ("file_hash", models.CharField(max_length=128)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("file_mtime_utc", models.DateTimeField(blank=True, null=True)),
                ("rows_read", models.BigIntegerField(default=0)),
                ("rows_inserted", models.BigIntegerField(default=0)),
                ("rows_updated", models.BigIntegerField(default=0)),
                ("rows_skipped", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flat_file_controls",
                        to="sync_jobs.syncjob",
                    ),
                ),
            ],
            options={
                "db_table": "flat_file_ingestion_controls",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="flatfileingestioncontrol",
            constraint=models.UniqueConstraint(
                fields=("job", "schema_name", "table_name", "file_name", "file_hash"),
                name="uniq_flat_file_control_job_table_file_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="flatfileingestioncontrol",
            index=models.Index(fields=["job", "-processed_at"], name="flat_file_i_job_id_3ae3fb_idx"),
        ),
        migrations.AddIndex(
            model_name="flatfileingestioncontrol",
            index=models.Index(fields=["job", "schema_name", "table_name"], name="flat_file_i_job_id_b8760d_idx"),
        ),
        migrations.AddIndex(
            model_name="flatfileingestioncontrol",
            index=models.Index(fields=["file_name", "file_hash"], name="flat_file_i_file_na_a38fd7_idx"),
        ),
        migrations.AddIndex(
            model_name="flatfileingestioncontrol",
            index=models.Index(fields=["status", "-processed_at"], name="flat_file_i_status_cc3a0f_idx"),
        ),
    ]
