# Generated by Django 4.2 on 2026-04-01 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0022_flatfile_hybrid_incremental"),
    ]

    operations = [
        migrations.CreateModel(
            name="MongoCdcCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                (
                    "resume_token",
                    models.TextField(
                        blank=True,
                        help_text="MongoDB resume token (stored as JSON/text) for Change Streams resumption",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mongo_cdc_checkpoints",
                        to="sync_jobs.syncjob",
                    ),
                ),
            ],
            options={
                "db_table": "mongo_cdc_checkpoints",
            },
        ),
        migrations.AddIndex(
            model_name="mongocdccheckpoint",
            index=models.Index(
                fields=["job", "schema_name", "table_name"],
                name="mongo_cdc_c_job_id_9b8052_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mongocdccheckpoint",
            unique_together={("job", "schema_name", "table_name")},
        ),
    ]
