# Generated by Django 4.2 on 2026-04-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0023_mongo_cdc_checkpoint"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="flatfileingestioncontrol",
            new_name="flat_file_i_job_id_811af3_idx",
            old_name="flat_file_i_job_id_3ae3fb_idx",
        ),
        migrations.RenameIndex(
            model_name="flatfileingestioncontrol",
            new_name="flat_file_i_job_id_0cf443_idx",
            old_name="flat_file_i_job_id_b8760d_idx",
        ),
        migrations.RenameIndex(
            model_name="flatfileingestioncontrol",
            new_name="flat_file_i_file_na_898fed_idx",
            old_name="flat_file_i_file_na_a38fd7_idx",
        ),
        migrations.RenameIndex(
            model_name="flatfileingestioncontrol",
            new_name="flat_file_i_status_842faf_idx",
            old_name="flat_file_i_status_cc3a0f_idx",
        ),
    ]
