# Generated by Django 4.2 on 2026-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sync_jobs",
            "0024_rename_flat_file_i_job_id_3ae3fb_idx_flat_file_i_job_id_811af3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="syncexecution",
            name="total_source_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncexecution",
            name="total_target_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncexecutionlog",
            name="source_size_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncexecutionlog",
            name="target_size_bytes",
            field=models.BigIntegerField(default=0),
        ),
    ]
