# Generated by Django 4.2 on 2026-04-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0027_syncexecution_db_size_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncexecutionlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
