# Generated by Django 4.2 on 2026-04-29 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0028_alter_syncexecutionlog_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncVerificationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schema_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                (
                    "sync_mode",
                    models.CharField(
                        choices=[("full", "Full"), ("incremental", "Incremental")],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("source_count", models.BigIntegerField(default=0)),
                ("target_count", models.BigIntegerField(default=0)),
                ("sample_hash_match", models.BooleanField(blank=True, null=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("repair_full", "Repair Full"),
                            ("repair_incremental", "Repair Incremental"),
                            ("warning", "Warning"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_reports",
                        to="sync_jobs.syncexecution",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_reports",
                        to="sync_jobs.syncjob",
                    ),
                ),
            ],
            options={
                "db_table": "sync_verification_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="syncverificationreport",
            index=models.Index(
                fields=["job", "-created_at"], name="sync_verifi_job_id_33e602_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncverificationreport",
            index=models.Index(
                fields=["job", "schema_name", "table_name"],
                name="sync_verifi_job_id_29b579_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncverificationreport",
            index=models.Index(
                fields=["decision"], name="sync_verifi_decisio_e963a4_idx"
            ),
        ),
    ]
