# Generated by Django 4.2 on 2026-04-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_jobs", "0029_add_sync_verification_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="verification_mode",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("sampled", "Sampled (count only)"),
                    ("strict", "Strict (count + hash, fail-on-drift)"),
                ],
                default="sampled",
                help_text="Post-run verification policy. 'strict' fails the run on parity mismatch; 'sampled' logs counts only; 'off' disables verification.",
                max_length=20,
            ),
        ),
    ]
